package com.csair.testlog.utils.listener;

import org.apache.log4j.Logger;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import java.sql.Connection;
import java.sql.DriverManager;

/**
 * 环境监听器
 *
 * @author LW_Fung
 */
public class ContextListener implements ServletContextListener {

    private static final Logger LOGGER = Logger.getLogger(ContextListener.class);

    public void contextInitialized(ServletContextEvent servletContextEvent) {
        /*容器启动后加载内存数据库并创建表*/
        try {
            Class.forName("org.hsqldb.jdbcDriver");
            Connection conn = DriverManager.getConnection("jdbc:hsqldb:mem:.", "sa", "");
            String createTableSQL = "CREATE TABLE APP_LOG(LOG_ID INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                    "LOG_TIME TIMESTAMP NOT NULL," +
                    "THREAD_NAME VARCHAR(50) NOT NULL," +
                    "LOG_LEVEL VARCHAR(20)," +
                    "CLASS_NAME VARCHAR(50)," +
                    "LOG_INFO VARCHAR(2000) NOT NULL, " +
                    "PRIMARY KEY (LOG_ID))";
            conn.prepareStatement(createTableSQL).execute();
        } catch (Exception e) {
            e.printStackTrace();
            LOGGER.error(e.getMessage());
        }
    }

    public void contextDestroyed(ServletContextEvent servletContextEvent) {
    }
}
